export const productos = [
    {id : 1 , 
    src : "Imagenes/Batman1.jpeg",
    tematica : "The Batman",
    modelo: "Batman - Diseño clasico" ,
    precio : 1200 ,
    categoria: "remera" 
    },
    
    {id : 2 ,
    src : "Imagenes/Anime1.jpeg",
    tematica : "Anime",
    modelo: "Goku" ,
    precio : 1500 ,
    categoria: "remera"
    },

    {id : 3 ,
    src : "Imagenes/Simpsons5.jpeg",
    tematica : "The Simpsons",
    modelo: "Tony El Gordo" ,
    precio : 1500 ,
    categoria: "remera"
    },
    {id : 4 , src : "Imagenes/Spiderman.jpeg", tematica : "Spiderman", modelo: "Spider-man" ,precio : 1500 ,categoria: "remera"},
    {id : 5 , src : "Imagenes/Anime6.jpeg", tematica : "Anime", modelo: "Itachi" ,precio : 1500 ,categoria: "remera"},
    {id : 6 , src : "Imagenes/Simpsons2.jpeg", tematica : "The Simpsons", modelo: "Homero" ,precio : 1000 ,categoria: "remera"},
    {id : 7 , src : "Imagenes/Batman2.jpeg", tematica : "The Batman", modelo: "Batman - Serie Animada" ,precio : 1800 ,categoria: "remera"},
    {id : 8 , src : "Imagenes/Batman4.jpeg", tematica : "The Batman", modelo: "Batman - White Bat" ,precio : 1700 ,categoria: "remera"},
    {id : 9 , src : "Imagenes/Batman5.jpeg", tematica : "The Batman", modelo: "Batman - Silueta" ,precio : 1000 ,categoria: "remera"},
    {id : 10 , src : "Imagenes/Simpsons1.jpeg", tematica : "The Simpsons", modelo: "Duffman" ,precio : 1000 ,categoria: "remera"},
    {id : 11 , src : "Imagenes/Batman3.jpeg", tematica : "The Batman", modelo: "Gotham Knight" ,precio : 1200 ,categoria: "remera"},
    {id : 12 , src : "Imagenes/Simpsons3.jpeg", tematica : "The Simpsons", modelo: "Kodos" ,precio : 1800 ,categoria: "remera"},
    {id : 13 , src : "Imagenes/Anime4.jpeg", tematica : "Anime", modelo: "Naruto" ,precio : 1500 ,categoria: "remera"},
    {id : 14 , src : "Imagenes/Anime2.jpeg", tematica : "Anime", modelo: "Jujutsu" ,precio : 1500 ,categoria: "remera"},
    {id : 15 , src : "Imagenes/Batman8.jpeg", tematica : "The Batman", modelo: "Batman/Joker" ,precio : 1200 ,categoria: "remera"},
    {id : 16 , src : "Imagenes/Anime8.jpeg", tematica : "Anime", modelo: "Trunks" ,precio : 1500 ,categoria: "remera"},
    {id : 17 , src : "Imagenes/CapsuleCorp.jpeg", tematica : "Anime", modelo: "Capsule Corp" ,precio : 3000 ,categoria: "buzo"},
    {id : 18 , src : "Imagenes/Hogwarts.jpeg", tematica : "Series y Peliculas", modelo: "Hogwarts" ,precio : 3000 ,categoria: "buzo"},
    {id : 19 , src : "Imagenes/Friends.jpeg", tematica : "Series y Peliculas", modelo: "Friends" ,precio : 3000 ,categoria: "buzo"},
    {id : 20 , src : "Imagenes/CobraKai.jpeg", tematica : "Series y Peliculas", modelo: "Cobra Kai" ,precio : 3000 ,categoria: "buzo"},
    {id : 21 , src : "Imagenes/Duff.jpeg", tematica : "The Simpsons", modelo: "Cerveza Duff" ,precio : 3000 ,categoria: "buzo"},
    {id : 22 , src : "Imagenes/YUYU.jpeg", tematica : "Anime", modelo: "Yuyu" ,precio : 3000 ,categoria: "buzo"},
    {id : 23 , src : "Imagenes/Osito.jpeg", tematica : "The Simpsons", modelo: "Osito Cariñosito" ,precio : 3000 ,categoria: "buzo"}
]
